config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  get "pages/home"
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :image, presence: true
  validates :description, presence: true
  validates :isbn, presence: true
  validates :price, presence: true
  validates :contact, presence: true
  validates :title, presence: true
  validates :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :isbn, :price, :contact, :title, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinboard", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
         <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Book
            <% end %>
          </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>



    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
		  <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<!DOCTYPE html>
<html>

<body>
  <h1>Lander Pinboard.</h1>
  <p>The most convenient way to buy or sell your textbook.</p>
        <p> 
          <br>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Join Now", new_user_registration_path, class: "btn btn-primary btn-lg"  %>
        </p>

         <br><br><br><br><br><br><br><br><br><br><br><br><br><br>


    <div class="textbooks for sale">
    <div class="container">
    <h4>
    <img src="http://i.imgur.com/sRp3gyt.jpg" alt="some_text" width="350" height="120"><br><br>
    <img src="http://i.imgur.com/QuAWIEL.jpg" alt="some_text" width="220" height="240">
    <img src="http://i.imgur.com/3DqmhA0.jpg?1?1791" alt="some_text" width="220" height="240">
     <img src="http://i.imgur.com/HfR4p8v.jpg" alt="some_text" width="220" height="240">
    </h4>
  </div>
</div>
</body>

</html>


  
<style>

body {
  background-image:url("http://farm3.staticflickr.com/2853/9728900510_7844d7828e_b.jpg");
  background-repeat: no-repeat;
  background-size: 1450px;
  background-position: relative;
  background-color: white;
}

h1 {
  padding-top: 200px;
  font-family: "Arial Black", Gadget, sans-serif; 
  font-size: 50px;
  color: #fff;
  font-weight: bold;
  text-transform: uppercase;
  text-align: left;
}

p {
  font-size: 20px;
  color: #fff;
  font-weight: bold;
  text-transform: uppercase;
  text-align: left;
}

h2 {
  font-size: 50px;
  font-weight: bold;
  border-radius: 50px;
  color: #940000;
}

h3 {
  font-weight: bold;
  font-size: 20px;
}

h4 {
  display: inline-block;
  float: center;
  clear: left;
}
pre {
  font-family: "Arial Black", Gadget, sans-serif;
}
.textbooks {
  padding-top: 235px;
  text-align: center;
  padding-bottom: 25px;
  color: black;
  font-size: 15px;
  font-family: 'Shift', sans-serif;
} 

.outer {
    text-align: justify;
}
.outer img {
    display: inline-block;
    vertical-align: center;
}

  </style> 
  

app/views/pages/about.html.erb
<div class="jumbotron center">
<div class="container">
        <h1>Finally, a Place to buy and sell</h1>
        <p>No more posting your textbooks on a messy pinboard. There's an app for that. </p> 

<style>
.jumbotron {
  background-image:url("http://i.imgur.com/LsxOWtp.jpg?1?7745");
  height: 520px;
}

.jumbotron .container {
  position: relative;
  top:110px;
}

.jumbotron h1 {
  color: #fff;
  font-size: 48px;  
  font-family: 'Shift', sans-serif;
  font-weight: bold;
}

.jumbotron p {
  font-size: 20px;
  color: #fff;
}");
  height: 510px;
}

.jumbotron .container {
  position: relative;
  top:110px;
}

.jumbotron h1 {
  color: #fff;
  font-size: 48px;  
  font-family: 'Shift', sans-serif;
  font-weight: bold;
}

.jumbotron p {
  font-size: 20px;
  color: #fff;
}
</style>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body"><strong>TITLE: </strong>
        <%= pin.title %><br/><strong>AUTHOR: </strong>
        <%= pin.author %><br/><strong>ISBN: </strong>#
        <%= pin.isbn %><br/><strong>PRICE: </strong>$
        <%= pin.price %><br/><strong>DESCRIPTION: </strong>
        <%= pin.description %><br/><strong>CONTACT: </strong><span class="glyphicon glyphicon-earphone"></span> <span class="glyphicon glyphicon-envelope"></span>
        <%= pin.contact %><br/>
        <span class="glyphicon glyphicon-user"></span>

        <strong><%= pin.user.name if pin.user %></strong>
        
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %> 
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Delete
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><strong>TITLE: </strong> <%= @pin.title %></p>
        <p><strong>AUTHOR: </strong><%= @pin.author %></p>
        <p><strong>ISBN: </strong># <%= @pin.isbn %></p>
        <p><strong>PRICE: </strong>$<%= @pin.price %></p>
        <p><strong>DESCRIPTION: </strong><%= @pin.description %></p>
        <p><strong>CONTACT: </strong><%= @pin.contact %> <span class="glyphicon glyphicon-earphone"></span> <span class="glyphicon glyphicon-envelope"></span></p>
        <p>
          <span class="glyphicon glyphicon-user"></span>
          <strong><%= @pin.user.name if @pin.user %></strong>
        </p>

        <% if @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>